#!/bin/bash

cp config/config.example.json config/config.json

node_modules/.bin/sequelize db:migrate
node_modules/.bin/sequelize db:seed:all

echo "Migration and seed done."

cd client
npm install
npm run build
echo "build client done."